version: "3.1"

services:
  tech-active-db:
    container_name: tech-active-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: tech-active-db
      MYSQL_USER: abhinav
      MYSQL_PASSWORD: abhinav
